### ISSUE TITLE
Bug: parse scene files includes possibly unnecessary files

### ISSUE THREAD

**Issue by lucaseck** [aws-deadline/deadline-cloud-for-houdini#122]
### Expected Behaviour

Parsing the scene for input files doesn't include unnecessary files or references that aren't actually files

### Current Behaviour

There are cases where files like `voptype.h voplib.h` are included in the Input Filenames after clicking Parse Files. These files don't appear to be needed for rendering and are skipped during submission as missing files.

There are other cases where [`op:` references](https://www.sidefx.com/docs/houdini/io/op_syntax.html) to other nodes are included in the input files and are also evaluated and skipped as missing files during upload.

### Reproduction Steps

To get the header files to be included:
- in /obj I created a new scene with a single light, geometry(cube), camera
- added a default texture material in /mat
- applied the material texture to the geometry node
- in /out created mantra and deadline cloud nodes
- clicked parse files on the deadline cloud node

The parsed files included:
`voptype.h voplib.h`

To get the `op:` references being included:
- I downloaded the `Rocket Launch` sample scene [provided by SideFX](https://www.sidefx.com/contentlibrary/)
- opened the `protonMfail_smoke.hip`
- in /out I added mantra and deadline cloud nodes
- clicked Parse Files in the deadline cloud node

The parsed files include:
`strcat("op:", opfullpath("sky_env_net/sky_env_map"))`

When submitted this evaluates to `- 'op:'` in the asset manifest and the upload is skipped as the file doesn't exist.

### Code Snippet

Some filtering on files to include vs not is already present [here](https://github.com/aws-deadline/deadline-cloud-for-houdini/blob/mainline/src/deadline/houdini_submitter/python/deadline_cloud_for_houdini/submitter.py#L53)

```
for parm, ref in hou.fileReferences():
        if parm:
            if parm.node() == rop_node:
                continue
            if ref.startswith(IGNORE_REF_VALUES):
                continue
            if parm.name() in IGNORE_REF_PARMS:
                continue
        if os.path.isdir(ref):
            continue
        input_filenames.add(ref)
```

Things like `opdef:", "oplib:", "temp:"` [are already being skipped](https://github.com/aws-deadline/deadline-cloud-for-houdini/blob/mainline/src/deadline/houdini_submitter/python/deadline_cloud_for_houdini/submitter.py#L27), but not `op:` if it should be skipped.

**Comment by crowecawcaw** [comment]
`op:` references were fixed/excluded in https://github.com/aws-deadline/deadline-cloud-for-houdini/pull/132. The other unnecessary files still need to be investigated.

**Comment by crowecawcaw** [comment]
Confirmed that other unnecessary files are also filtered out as a result of https://github.com/aws-deadline/deadline-cloud-for-houdini/pull/132.
